# Generated by Django 5.0.6 on 2024-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.JSONField(default={'city': '', 'geo_location': {'lat': 0.0, 'lng': 0.0}, 'street': '', 'suite': '', 'zip_code': ''})),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('company', models.JSONField(default={'BS': '', 'catchPhrase': '', 'name': ''})),
            ],
        ),
    ]
