# Generated by Django 5.0.6 on 2024-06-13 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 10, 46, 20, 42348)),
        ),
        migrations.AddField(
            model_name='userappmodel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 10, 46, 20, 42366)),
        ),
    ]
